"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, multiprocessing, json

SECRET_KEY = None
DEBUG = None
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALLOWED_HOSTS = ['*']

# 覆盖设置，动态调整参数
try:
    with open(os.path.join(BASE_DIR, 'setup.json')) as f:
        data = json.load(f)
    for k, v in data.items():
        globals()[k] = v
        if isinstance(v, str):
            os.environ[k] = v
except:
    raise

# 自动生成的设置
if 'original':
    INSTALLED_APPS = [
        'usr_sys',
        'oj',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF = 'main.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [os.path.join(BASE_DIR, 'templates')],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
                'libraries': {
                    'main_filters': 'main.filters',
                }
            },
        },
    ]

    WSGI_APPLICATION = 'main.wsgi.application'

    # Windows与Linux下数据库后端
    if os.sys.platform == 'win32':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'database.db'),
            }
        }
    else:
        import pymysql
        pymysql.install_as_MySQLdb()

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'pyfillin_oj',
                'USER': os.environ['MYSQL_USER'],
                'PASSWORD': os.environ['MYSQL_PASSWD'],
                'HOST': os.environ['MYSQL_HOST'],
                'PORT': os.environ['MYSQL_PORT'],
            }
        }

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]
    LANGUAGE_CODE = 'zh-hans'
    TIME_ZONE = 'Asia/Shanghai'
    USE_I18N = True
    USE_L10N = True
    USE_TZ = False

    STATIC_URL = '/assets/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'assets')
    if os.sys.platform == 'win32':
        STATICFILES_DIRS = [os.path.join(BASE_DIR, 'assets')]
        del STATIC_ROOT

    MEDIA_URL = '/_STORAGE/'
    MEDIA_ROOT = os.path.join(BASE_DIR, '_STORAGE')

# 合法字符集合
RAND_CHARPOOL = 'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789_'  # 用于生成随机字符串
USERNAME_CHARPOOL = set(RAND_CHARPOOL)  # 用于匹配用户名

# 邮件bot系统
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.pku.edu.cn'
EMAIL_PORT = 25
# EMAIL_HOST_USER, EMAIL_HOST_PASSWORD

# 验证邮件配置参数
EMAIL_VALID_RESEND_MINUTES = 5  # 每{}分钟可重发一次验证邮件
EMAIL_VALID_LAST_DAYS = 5  # 每封验证邮件内链接有效期为{}天

# =====================OJ设置=====================
SUBMISSION_STATUS=(
    (0,'已提交'),
    (1,'运行中'),
    (2,'已通过'),
    (3,'未通过'),
)